Theory and Practice of FEM -- a parametrized Poisson Solver: LinearElasticity< dim > Class Template Reference
LinearElasticity< dim > Class Template Reference
#include <linear_elasticity.h>
Public Types
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
using ScratchData = MeshWorker::ScratchData< dim >
Public Member Functions
LinearElasticity ()
void print_system_info ()
void run ()
void initialize (const std::string &filename)
void parse_string (const std::string &par)
Protected Member Functions
void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
void copy_one_cell (const CopyData &copy)
void make_grid ()
void refine_grid ()
void setup_system ()
void assemble_system ()
void assemble_system_on_range (const typename DoFHandler< dim >::active_cell_iterator &begin, const typename DoFHandler< dim >::active_cell_iterator &end)
void solve ()
void estimate ()
void mark ()
void output_results (const unsigned cycle) const
Protected Attributes
MPI_Comm mpi_communicator
ConditionalOStream pcout
TimerOutput timer
const unsigned int n_components
parallel::distributed::Triangulation< dim > triangulation
std::unique_ptr< FiniteElement< dim > > fe
std::unique_ptr< MappingQGeneric< dim > > mapping
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
LA::MPI::SparseMatrix system_matrix
LA::MPI::Vector locally_relevant_solution
LA::MPI::Vector solution
LA::MPI::Vector system_rhs
Vector< float > error_per_cell
std::string estimator_type = "kelly"
std::string marking_strategy = "global"
std::pair< double, double > coarsening_and_refinement_factors = { 0.03, 0.3 }
FunctionParser< dim > pre_refinement
FunctionParser< dim > coefficient
FunctionParser< dim > forcing_term
FunctionParser< dim > exact_solution
FunctionParser< dim > dirichlet_boundary_condition
FunctionParser< dim > neumann_boundary_condition
std::string fe_name = "FESystem[FE_Q(1)^d]"
unsigned int mapping_degree = 1
unsigned int n_refinements = 4
unsigned int n_refinement_cycles = 1
std::string output_filename = "linear_elasticity"
int number_of_threads = -1
std::set< types::boundary_id > dirichlet_ids = { 0 }
std::set< types::boundary_id > neumann_ids
std::string forcing_term_expression = "0; -1"
std::string coefficient_expression = "1"
std::string exact_solution_expression = "0; 0"
std::string dirichlet_boundary_conditions_expression = "0; 0"
std::string neumann_boundary_conditions_expression = "0; 0"
std::string pre_refinement_expression = "0"
std::map< std::string, double > constants
std::string grid_generator_function = "hyper_cube"
std::string grid_generator_arguments = "0: 1: true"
ParsedConvergenceTable error_table
bool use_direct_solver = true
ParameterAcceptorProxy< ReductionControl > solver_control
FEValuesExtractors::Vector velocity
double mu = 1.0
double lambda = 1.0
Friends
template<typename Integral >
class LinearElasticityTester
Additional Inherited Members
Private Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Static Private Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Private Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Private Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
const std::string section_name
std::vector< std::string > subsections
Static Private Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class LinearElasticity< dim >
Solve the LinearElasticity problem, with Dirichlet or Neumann boundary conditions, on all geometries that can be generated by the functions in the GridGenerator namespace.
Definition at line 71 of file linear_elasticity.h.
Member Typedef Documentation
CopyData
template<int dim> using LinearElasticity< dim >::CopyData = MeshWorker::CopyData<1, 1, 1>
Definition at line 91 of file linear_elasticity.h.
ScratchData
template<int dim> using LinearElasticity< dim >::ScratchData = MeshWorker::ScratchData<dim>
Definition at line 92 of file linear_elasticity.h.
Constructor & Destructor Documentation
LinearElasticity()
template<int dim> LinearElasticity< dim >::LinearElasticity
Constructor. Initialize all parameters, and make sure the class is ready to run.
Definition at line 22 of file linear_elasticity.cc.
References ParameterAcceptor::add_parameter(), ParsedConvergenceTable::add_parameters(), LinearElasticity< dim >::coarsening_and_refinement_factors, LinearElasticity< dim >::coefficient_expression, LinearElasticity< dim >::constants, LinearElasticity< dim >::dirichlet_boundary_conditions_expression, LinearElasticity< dim >::dirichlet_ids, e(), ParameterHandler::enter_subsection(), LinearElasticity< dim >::error_table, LinearElasticity< dim >::estimator_type, LinearElasticity< dim >::exact_solution_expression, LinearElasticity< dim >::fe_name, LinearElasticity< dim >::forcing_term_expression, LinearElasticity< dim >::grid_generator_arguments, LinearElasticity< dim >::grid_generator_function, LinearElasticity< dim >::lambda, ParameterHandler::leave_subsection(), LinearElasticity< dim >::mapping_degree, LinearElasticity< dim >::marking_strategy, LinearElasticity< dim >::n_refinement_cycles, LinearElasticity< dim >::n_refinements, LinearElasticity< dim >::neumann_boundary_conditions_expression, LinearElasticity< dim >::neumann_ids, LinearElasticity< dim >::number_of_threads, LinearElasticity< dim >::output_filename, LinearElasticity< dim >::pre_refinement_expression, ParameterAcceptor::prm, this_mpi_process(), LinearElasticity< dim >::timer, triangulation, and LinearElasticity< dim >::use_direct_solver.
Member Function Documentation
assemble_system()
template<int dim> void LinearElasticity< dim >::assemble_system protected
Definition at line 258 of file linear_elasticity.cc.
References VectorOperation::add, copy(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_on_range()
template<int dim> void LinearElasticity< dim >::assemble_system_on_range (const typename DoFHandler< dim >::active_cell_iterator & begin, const typename DoFHandler< dim >::active_cell_iterator & end) protected
Definition at line 234 of file linear_elasticity.cc.
References begin(), copy(), end(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_one_cell()
template<int dim> void LinearElasticity< dim >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) protected
Definition at line 175 of file linear_elasticity.cc.
References cell_matrix(), copy(), lambda, MeshWorker::ScratchData< dim, spacedim >::reinit(), and scalar_product().
copy_one_cell()
template<int dim> void LinearElasticity< dim >::copy_one_cell (const CopyData & copy) protected
Definition at line 228 of file linear_elasticity.cc.
References copy().
estimate()
template<int dim> void LinearElasticity< dim >::estimate protected
Definition at line 301 of file linear_elasticity.cc.
References AssertThrow, cell_index, KellyErrorEstimator< dim, spacedim >::estimate(), ExcNotImplemented(), FEValues< dim >::get_function_laplacians(), VectorTools::H1_seminorm, VectorTools::integrate_difference(), FEValues< dim >::JxW(), FEValues< dim >::quadrature_point(), FEValues< dim >::quadrature_point_indices(), FEValues< dim >::reinit(), QGauss< dim >::size(), update_hessians, update_JxW_values, and update_quadrature_points.
initialize()
template<int dim> void LinearElasticity< dim >::initialize (const std::string & filename)
Definition at line 79 of file linear_elasticity.cc.
References ParameterAcceptor::initialize(), and ParameterHandler::Short.
Referenced by main().
make_grid()
template<int dim> void LinearElasticity< dim >::make_grid protected
Definition at line 93 of file linear_elasticity.cc.
References GridGenerator::generate_from_name_and_arguments(), lambda, and triangulation.
mark()
template<int dim> void LinearElasticity< dim >::mark protected
Definition at line 371 of file linear_elasticity.cc.
References Assert, ExcInternalError(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), and triangulation.
output_results()
template<int dim> void LinearElasticity< dim >::output_results (const unsigned cycle) const protected
Definition at line 392 of file linear_elasticity.cc.
References DataOut< dim >::add_data_vector(), DataOut< dim >::attach_dof_handler(), DataOut< dim >::build_patches(), DataComponentInterpretation::component_is_part_of_vector, DataOut< dim >::set_flags(), triangulation, DataOutBase::VtkFlags::write_higher_order_cells, GridOut::write_mesh_per_processor_as_vtu(), and DataOut< dim >::write_vtu_in_parallel().
parse_string()
template<int dim> void LinearElasticity< dim >::parse_string (const std::string & par)
Definition at line 86 of file linear_elasticity.cc.
References ParameterAcceptor::parse_all_parameters(), ParameterHandler::parse_input_from_string(), and ParameterAcceptor::prm.
print_system_info()
template<int dim> void LinearElasticity< dim >::print_system_info
Definition at line 426 of file linear_elasticity.cc.
References MultithreadInfo::n_cores(), MultithreadInfo::n_threads(), and MultithreadInfo::set_thread_limit().
refine_grid()
template<int dim> void LinearElasticity< dim >::refine_grid protected
Definition at line 116 of file linear_elasticity.cc.
References triangulation.
run()
template<int dim> void LinearElasticity< dim >::run
Definition at line 437 of file linear_elasticity.cc.
Referenced by main().
setup_system()
template<int dim> void LinearElasticity< dim >::setup_system protected
Definition at line 123 of file linear_elasticity.cc.
References SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), VectorTools::interpolate_boundary_values(), locally_owned_dofs(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), and triangulation.
solve()
template<int dim> void LinearElasticity< dim >::solve protected
Definition at line 281 of file linear_elasticity.cc.
References SolverCG< VectorType >::solve().
Friends And Related Function Documentation
LinearElasticityTester
template<int dim> template<typename Integral > friend class LinearElasticityTester friend
Definition at line 199 of file linear_elasticity.h.
Member Data Documentation
coarsening_and_refinement_factors
template<int dim> std::pair<double, double> LinearElasticity< dim >::coarsening_and_refinement_factors = { 0.03, 0.3 } protected
Definition at line 154 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
coefficient
template<int dim> FunctionParser<dim> LinearElasticity< dim >::coefficient protected
Definition at line 158 of file linear_elasticity.h.
coefficient_expression
template<int dim> std::string LinearElasticity< dim >::coefficient_expression = "1" protected
Definition at line 177 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
constants
template<int dim> std::map<std::string, double> LinearElasticity< dim >::constants protected
Definition at line 182 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
constraints
template<int dim> AffineConstraints<double> LinearElasticity< dim >::constraints protected
Definition at line 140 of file linear_elasticity.h.
dirichlet_boundary_condition
template<int dim> FunctionParser<dim> LinearElasticity< dim >::dirichlet_boundary_condition protected
Definition at line 163 of file linear_elasticity.h.
dirichlet_boundary_conditions_expression
template<int dim> std::string LinearElasticity< dim >::dirichlet_boundary_conditions_expression = "0; 0" protected
Definition at line 179 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
dirichlet_ids
template<int dim> std::set<types::boundary_id> LinearElasticity< dim >::dirichlet_ids = { 0 } protected
Definition at line 173 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
dof_handler
template<int dim> DoFHandler<dim> LinearElasticity< dim >::dof_handler protected
Definition at line 139 of file linear_elasticity.h.
error_per_cell
template<int dim> Vector<float> LinearElasticity< dim >::error_per_cell protected
Definition at line 151 of file linear_elasticity.h.
error_table
template<int dim> ParsedConvergenceTable LinearElasticity< dim >::error_table protected
Definition at line 187 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
estimator_type
template<int dim> std::string LinearElasticity< dim >::estimator_type = "kelly" protected
Definition at line 152 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
exact_solution
template<int dim> FunctionParser<dim> LinearElasticity< dim >::exact_solution protected
Definition at line 162 of file linear_elasticity.h.
exact_solution_expression
template<int dim> std::string LinearElasticity< dim >::exact_solution_expression = "0; 0" protected
Definition at line 178 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
fe
template<int dim> std::unique_ptr<FiniteElement<dim> > LinearElasticity< dim >::fe protected
Definition at line 137 of file linear_elasticity.h.
fe_name
template<int dim> std::string LinearElasticity< dim >::fe_name = "FESystem[FE_Q(1)^d]" protected
Definition at line 166 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
forcing_term
template<int dim> FunctionParser<dim> LinearElasticity< dim >::forcing_term protected
Definition at line 161 of file linear_elasticity.h.
forcing_term_expression
template<int dim> std::string LinearElasticity< dim >::forcing_term_expression = "0; -1" protected
Definition at line 176 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
grid_generator_arguments
template<int dim> std::string LinearElasticity< dim >::grid_generator_arguments = "0: 1: true" protected
Definition at line 185 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
grid_generator_function
template<int dim> std::string LinearElasticity< dim >::grid_generator_function = "hyper_cube" protected
Definition at line 184 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
lambda
template<int dim> double LinearElasticity< dim >::lambda = 1.0 protected
Definition at line 196 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
locally_owned_dofs
template<int dim> IndexSet LinearElasticity< dim >::locally_owned_dofs protected
Definition at line 143 of file linear_elasticity.h.
locally_relevant_dofs
template<int dim> IndexSet LinearElasticity< dim >::locally_relevant_dofs protected
Definition at line 144 of file linear_elasticity.h.
locally_relevant_solution
template<int dim> LA::MPI::Vector LinearElasticity< dim >::locally_relevant_solution protected
Definition at line 147 of file linear_elasticity.h.
mapping
template<int dim> std::unique_ptr<MappingQGeneric<dim> > LinearElasticity< dim >::mapping protected
Definition at line 138 of file linear_elasticity.h.
mapping_degree
template<int dim> unsigned int LinearElasticity< dim >::mapping_degree = 1 protected
Definition at line 167 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
marking_strategy
template<int dim> std::string LinearElasticity< dim >::marking_strategy = "global" protected
Definition at line 153 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
mpi_communicator
template<int dim> MPI_Comm LinearElasticity< dim >::mpi_communicator protected
Definition at line 129 of file linear_elasticity.h.
mu
template<int dim> double LinearElasticity< dim >::mu = 1.0 protected
Definition at line 195 of file linear_elasticity.h.
n_components
template<int dim> const unsigned int LinearElasticity< dim >::n_components protected
Definition at line 134 of file linear_elasticity.h.
n_refinement_cycles
template<int dim> unsigned int LinearElasticity< dim >::n_refinement_cycles = 1 protected
Definition at line 169 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
n_refinements
template<int dim> unsigned int LinearElasticity< dim >::n_refinements = 4 protected
Definition at line 168 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
neumann_boundary_condition
template<int dim> FunctionParser<dim> LinearElasticity< dim >::neumann_boundary_condition protected
Definition at line 164 of file linear_elasticity.h.
neumann_boundary_conditions_expression
template<int dim> std::string LinearElasticity< dim >::neumann_boundary_conditions_expression = "0; 0" protected
Definition at line 180 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
neumann_ids
template<int dim> std::set<types::boundary_id> LinearElasticity< dim >::neumann_ids protected
Definition at line 174 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
number_of_threads
template<int dim> int LinearElasticity< dim >::number_of_threads = -1 protected
Definition at line 171 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
output_filename
template<int dim> std::string LinearElasticity< dim >::output_filename = "linear_elasticity" protected
Definition at line 170 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
pcout
template<int dim> ConditionalOStream LinearElasticity< dim >::pcout protected
Definition at line 131 of file linear_elasticity.h.
pre_refinement
template<int dim> FunctionParser<dim> LinearElasticity< dim >::pre_refinement protected
Definition at line 157 of file linear_elasticity.h.
pre_refinement_expression
template<int dim> std::string LinearElasticity< dim >::pre_refinement_expression = "0" protected
Definition at line 181 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
solution
template<int dim> LA::MPI::Vector LinearElasticity< dim >::solution protected
Definition at line 148 of file linear_elasticity.h.
solver_control
template<int dim> ParameterAcceptorProxy<ReductionControl> LinearElasticity< dim >::solver_control protected
Definition at line 191 of file linear_elasticity.h.
system_matrix
template<int dim> LA::MPI::SparseMatrix LinearElasticity< dim >::system_matrix protected
Definition at line 146 of file linear_elasticity.h.
system_rhs
template<int dim> LA::MPI::Vector LinearElasticity< dim >::system_rhs protected
Definition at line 149 of file linear_elasticity.h.
timer
template<int dim> TimerOutput LinearElasticity< dim >::timer mutable protected
Definition at line 132 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
triangulation
template<int dim> parallel::distributed::Triangulation<dim> LinearElasticity< dim >::triangulation protected
Definition at line 136 of file linear_elasticity.h.
use_direct_solver
template<int dim> bool LinearElasticity< dim >::use_direct_solver = true protected
Definition at line 189 of file linear_elasticity.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
velocity
template<int dim> FEValuesExtractors::Vector LinearElasticity< dim >::velocity protected
Definition at line 192 of file linear_elasticity.h.
The documentation for this class was generated from the following files:
/github/workspace/include/linear_elasticity.h
/github/workspace/source/linear_elasticity.cc